#!/usr/bin/env python3
"""
Generate SVG circle elements for the market map from config.py SEARCHES.

Uses Albers Equal-Area Conic projection (standard US map) to convert
lat/lng bounding-box centroids to SVG coordinates in a 960×600 viewBox.

Usage:
    python scripts/gen_market_dots.py

Output:  Prints <g> elements for pasting into the SVG, plus a count check.
         Also writes frontend/market-dots.js (shared data for both pages).
"""

import math
import os
import sys

# Add project root so we can import config
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from fsbo_tracker.config import SEARCHES


# ── Albers Equal-Area Conic projection (continental US) ──────────────
def albers_project(lat: float, lng: float) -> tuple[float, float]:
    """Project lat/lng to x,y using Albers USA parameters scaled to 960×600."""
    to_rad = math.pi / 180
    lng0 = -96.0 * to_rad
    lat0 = 38.0 * to_rad
    phi1 = 29.5 * to_rad
    phi2 = 45.5 * to_rad

    n = 0.5 * (math.sin(phi1) + math.sin(phi2))
    C = math.cos(phi1) ** 2 + 2 * n * math.sin(phi1)
    rho0 = math.sqrt(C - 2 * n * math.sin(lat0)) / n

    phi = lat * to_rad
    lam = lng * to_rad
    theta = n * (lam - lng0)
    rho = math.sqrt(C - 2 * n * math.sin(phi)) / n

    x = rho * math.sin(theta)
    y = rho0 - rho * math.cos(theta)

    # Scale & translate to fit 960×600 viewBox
    return round(480 + x * 1070, 1), round(260 - y * 1070, 1)


# ── Friendly display name from market ID ─────────────────────────────
STATE_MAP = {
    "nc": "NC", "tn": "TN", "fl": "FL", "ga": "GA", "pa": "PA", "tx": "TX",
    "oh": "OH", "mi": "MI", "in": "IN", "mo": "MO", "ky": "KY", "sc": "SC",
    "al": "AL", "ar": "AR", "ok": "OK", "wi": "WI", "va": "VA", "md": "MD",
    "nv": "NV", "az": "AZ", "co": "CO", "ut": "UT",
}


def display_name(market_id: str) -> str:
    parts = market_id.rsplit("-", 1)
    city = parts[0].replace("-", " ").title()
    state = STATE_MAP.get(parts[-1], parts[-1].upper()) if len(parts) > 1 else ""
    # Fix common title-case issues
    city = city.replace("St ", "St. ")
    return f"{city}, {state}" if state else city


# ── Generate ─────────────────────────────────────────────────────────
def main():
    markets = []
    svg_lines = []

    for i, s in enumerate(SEARCHES):
        center_lat = (s["min_lat"] + s["max_lat"]) / 2
        center_lng = (s["min_lng"] + s["max_lng"]) / 2
        cx, cy = albers_project(center_lat, center_lng)
        name = display_name(s["id"])
        delay = i * 30

        svg_lines.append(
            f'        <a class="market-dot" href="/app" tabindex="0" '
            f'role="link" aria-label="{name}" style="animation-delay:{delay}ms">'
            f'<circle cx="{cx}" cy="{cy}" r="5"/>'
            f'<title>{name}</title></a>'
        )

        markets.append({
            "id": s["id"],
            "name": name,
            "cx": cx,
            "cy": cy,
        })

    # Print SVG snippet
    print(f"<!-- {len(SEARCHES)} market dots (auto-generated by scripts/gen_market_dots.py) -->")
    print(f"<!-- Count check: SEARCHES={len(SEARCHES)} dots={len(svg_lines)} -->")
    for line in svg_lines:
        print(line)

    # Write shared JS data file
    js_path = os.path.join(os.path.dirname(__file__), "..", "frontend", "market-dots.js")
    with open(js_path, "w") as f:
        f.write("// Auto-generated by scripts/gen_market_dots.py — do not edit manually\n")
        f.write(f"// Count: {len(markets)} markets (must match backend SEARCHES)\n")
        f.write("const MARKET_DOTS = [\n")
        for m in markets:
            f.write(f'  {{id:"{m["id"]}",name:"{m["name"]}",cx:{m["cx"]},cy:{m["cy"]}}},\n')
        f.write("];\n")

    print(f"\n✓ {len(markets)} markets projected. JS written to frontend/market-dots.js", file=sys.stderr)

    # Sanity check
    if len(markets) != len(SEARCHES):
        print(f"⚠ COUNT MISMATCH: {len(markets)} dots vs {len(SEARCHES)} SEARCHES!", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
